modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "wagyourminimap"
version = "${version}"
displayName = "WagYourMinimap"
authors = "Wagyourtail"
description = '''
Minimap mod coded from scratch to not be ass.
'''
#logoFile = ""

[[dependencies.wagyourminimap]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wagyourminimap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wagyourminimap]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wagyourminimap]]
modId = "cloth_config"
mandatory = true
versionRange = "[5.0.38,)"
ordering = "AFTER"
side = "BOTH"