# This is a basic workflow to help you get started with Actions

name: Build Release V2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ created ]

jobs:
  build_1_18:
    uses: wagyourtail/wagyourminimap/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: main-1.18
      java_version: 17

  build_1_17:
    uses: wagyourtail/wagyourminimap/.github/workflows/releasebuild.yml@main-1.18
    with:
      branch: backport-1.17.1
      java_version: 16

  deploy_1_18:
    uses: wagyourtail/wagyourminimap/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: main-1.18
      cf_data_fabric: 73250:1.18,2:Java 17,68441:Fabric
      cf_data_forge: 73250:1.18,2:Java 17,7498:Forge
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - build_1_18
      - deploy_1_17

  deploy_1_17:
    uses: wagyourtail/wagyourminimap/.github/workflows/releasedeploy.yml@main-1.18
    with:
      branch: backport-1.17.1
      cf_data_fabric: 73242:1.17.1,2:Java 16,68441:Fabric
      cf_data_forge: 73242:1.17.1,2:Java 16,7498:Forge
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - build_1_17